solution
mate-academy/react_pagination pull request #148
Opened 2022-07-20 11:50 UTC by NikitaKarbazin

[DEMO LINK](https://nikitakarbazin.github.io/react_pagination/)

2022-07-25 07:20 UTC, averstiuk approved these changes
Залишила декілька коментів, а в цілому GJ, все працює))

2022-07-25 07:20 UTC, averstiuk commented on src/App.tsx
> +
зайвий рядок)

2022-07-25 07:20 UTC, averstiuk commented on src/App.tsx
> +      />
тут би треба додати рядок для кращої читабельності

2022-07-25 07:20 UTC, averstiuk commented on src/components/Pagination.tsx
> +      </button>
не вистачає пустих рядків між тегами одного рівня, коли в них багато атрибутів

2022-07-27 06:54 UTC, Olexandr6 approved these changes
Good job👍 Let's improve your solution a bit👇

2022-07-27 06:54 UTC, Olexandr6 commented on src/App.css
> +}
Should be moved to Pagination.css

2022-07-27 06:54 UTC, Olexandr6 commented on src/App.tsx
> +  const [perPage, setPerPage] = useState(5);
```suggestion
  const [itemsPerPage, setPerPage] = useState(5);
```

2022-07-27 06:54 UTC, Olexandr6 commented on src/App.tsx
> +  const [page, setPage] = useState(1);
Mb, `selectedPage`?

2022-07-27 06:54 UTC, Olexandr6 commented on src/App.tsx
> +  const [total] = useState(42);
What is total? Rename this var

2022-07-27 06:54 UTC, Olexandr6 commented on src/App.tsx
> +  const [inf, setInf] = useState(`${1}-${perPage} of ${total}`);
What is `inf`? Should be renamed

2022-07-27 06:54 UTC, Olexandr6 commented on src/App.tsx
> +  const info = () => {
How do we name functions? Name should start with a verb

2022-07-27 06:54 UTC, Olexandr6 commented on src/App.tsx
> +  };
Read more about handler naming - https://javascript.plainenglish.io/handy-naming-conventions-for-event-handler-functions-props-in-react-fc1cbb791364
```suggestion
  const handlePageChange = (pageFromComponent: number) => {
    setPage(pageFromComponent);
  };

  const handlePerPageChange = (perPageFromComponent: number) => {
    setPerPage(perPageFromComponent);
  };
```

2022-07-27 06:54 UTC, Olexandr6 requested changes
Check @averstiuk commments, as well

2022-07-27 07:27 UTC, Olexandr6 approved these changes

2023-10-07 15:27 UTC, closed without merging