Develop
mate-academy/react_pagination pull request #173
Opened 2022-08-17 09:17 UTC by Kras4iy

[DEMO LINK](https://Kras4iy.github.io/react_pagination/)

2022-08-17 17:27 UTC, TwoAndMore requested changes

2022-08-17 17:27 UTC, TwoAndMore commented on src/components/Pagination/Pagination.tsx
> +import { getNumbers } from '../../utils';
You don't need to import getNumbers there

2022-08-17 17:27 UTC, TwoAndMore commented on src/components/Pagination/Pagination.tsx
> +  const lastPageId = Math.ceil(total / perPage);
```suggestion
  const pageAmount= Math.ceil(total / perPage);
```
```suggestion
  const numberOfPages= Math.ceil(total / perPage);
```

2022-08-17 17:27 UTC, TwoAndMore commented on src/components/Pagination/Pagination.tsx
> +      <li className={`page-item ${currentPage === 1 ? 'disabled' : ''}`}>
You can use classNames

2022-08-17 17:27 UTC, TwoAndMore commented on src/components/Pagination/Pagination.tsx
> +          aria-disabled="true"
1. `«` and `»` links should open the prev and the next pages accordingly
    - disable each of them if it is already the first or the last page (use `li.disabled` and `a[aria-disabled="true"]`)

2022-08-17 17:27 UTC, TwoAndMore commented on src/components/Pagination/Pagination.tsx
> +      {getNumbers(1, lastPageId).map(number => (
```suggestion
      {[...Array(length)]).map(number => (
```

2022-08-17 17:27 UTC, TwoAndMore commented on src/components/Pagination/Pagination.tsx
> +          aria-disabled="false"
1. `«` and `»` links should open the prev and the next pages accordingly
    - disable each of them if it is already the first or the last page (use `li.disabled` and `a[aria-disabled="true"]`)

2022-08-17 17:27 UTC, TwoAndMore commented on src/components/Pagination/Pagination.tsx
> +    onPageChange((prevPage: number) => prevPage + step);
You can use ```currentPage```

2022-08-18 16:03 UTC, solaryasha requested changes

2022-08-18 16:03 UTC, solaryasha commented on src/App.tsx
> +        ${amountOfItems})`}
Let's create the separate variables, it's would easier to support this messages

2022-08-19 07:37 UTC, VETALEK approved these changes
GJ 🔥

2026-04-28 18:14 UTC, closed without merging