solution
mate-academy/react_pagination pull request #306
Opened 2023-01-21 23:46 UTC by batstolya

[DEMO LINK](https://batstolya.github.io/react_pagination/)

2023-01-25 14:30 UTC, romanblyashuk94 requested changes
basically everything is fine, just fix few variables names and remove redundant checkings

2023-01-25 14:30 UTC, romanblyashuk94 commented on src/components/Pagination/Pagination.tsx
> +  const pageItem = new Array(countPageItem).fill(1).map((_, i) => i + 1);
```suggestion
  const pageItems = new Array(countPageItem).fill(1).map((_, i) => i + 1);
```

2023-01-25 14:30 UTC, romanblyashuk94 commented on src/App.tsx
> +  const itemsSpliced = [...items].splice((currentPage - 1) * option, option);
```suggestion
  const splicedItems = [...items].splice((currentPage - 1) * option, option);
```

2023-01-25 14:30 UTC, romanblyashuk94 commented on src/App.tsx
> +  const [option, setOption] = useState<number>(5);
```suggestion
  const [perPageOption, setPerPageOption] = useState<number>(5);
```

2023-02-05 10:39 UTC, romanblyashuk94 approved these changes
Goodd job 🔥

2023-02-06 08:58 UTC, valerii-derkach approved these changes

2026-07-13 23:07 UTC, closed without merging