Develop
mate-academy/react_pagination pull request #351
Opened 2023-03-08 16:08 UTC by vanyachyzh

[DEMO LINK](https://vanyachyzh.github.io/react_pagination/)

2023-03-08 16:55 UTC, Viktor-Kost requested changes
Pretty nice. Need some improvements

2023-03-08 16:55 UTC, Viktor-Kost commented on src/App.tsx
> +  const [total] = useState(items);
it looks like a state for items, not for total

2023-03-08 16:55 UTC, Viktor-Kost commented on src/App.tsx
> +  );
move this function outside the component

2023-03-08 16:55 UTC, Viktor-Kost commented on src/App.tsx
> +  };
move as well

2023-03-08 16:55 UTC, Viktor-Kost commented on src/App.tsx
> +  const [currentPage, setCurrentPage] = useState(0);
how page can be with a 0 value? it should start from 1

2023-03-09 10:24 UTC, sTorba24 requested changes
Good work! Some suggestions to improve it :)

2023-03-09 10:24 UTC, sTorba24 commented on src/App.tsx
> +  const [currentPage, setCurrentPage] = useState(1);
you can store start values in variables to not use 'magic values'

2023-03-09 10:24 UTC, sTorba24 commented on src/components/Pagination/Pagination.tsx
> +    if (currentPage === items.length - 1) {
seems you are comparing page number and length of items array(42)?
You should check if page is not last, so currentPage === lastPage?

2023-03-09 10:24 UTC, sTorba24 commented on src/components/Pagination/Pagination.tsx
> +    if (currentPage === 0) {
```suggestion
    if (currentPage === 1) {
```

2023-03-09 10:24 UTC, sTorba24 commented on src/components/Pagination/Pagination.tsx
> +    if (currentPage === 0) {
Current page can be 0?

2023-03-09 10:24 UTC, sTorba24 commented on src/components/Pagination/Pagination.tsx
> +              disabled: currentPage === 1,
you can use variable like `isLastPage`

2023-03-09 10:24 UTC, sTorba24 commented on src/components/Pagination/Pagination.tsx
> +              disabled: currentPage === numLastPage,
`isLastPage`

2023-03-09 13:27 UTC, IvanFesenko approved these changes
Well done

2024-03-07 18:38 UTC, closed without merging