first commit
mate-academy/react_pagination pull request #47
Opened 2020-09-09 01:40 UTC by zarva6596

[DEMO LINK](https://zarva6596.github.io/react_pagination/)

2020-09-09 13:13 UTC, Denchepornyuk requested changes

2020-09-09 13:13 UTC, Denchepornyuk commented on src/Components/List/List.jsx
> +                      || button === buttons.length)
це краще винести в окруму функцію

2020-09-09 13:13 UTC, Denchepornyuk commented on src/Components/List/List.jsx
> +                    || button === buttons.length) ? button : '.'}
код повторюється точно протрібно виносити

2020-09-09 13:13 UTC, Denchepornyuk commented on src/Components/List/List.jsx
> +export class List extends React.Component {
List -> Pagination

2020-09-09 13:13 UTC, Denchepornyuk commented on src/Components/List/List.jsx
> +        </div>
було б добре розділити пагінацію від загального списку на дві компоненти

2020-09-09 21:00 UTC, zarva6596 commented on src/Components/List/List.jsx
> +                      || button === buttons.length)
готово

2020-09-09 21:00 UTC, zarva6596 commented on src/Components/List/List.jsx
> +                    || button === buttons.length) ? button : '.'}
готово

2020-09-09 21:01 UTC, zarva6596 commented on src/Components/List/List.jsx
> +export class List extends React.Component {
готово

2020-09-09 22:37 UTC, zarva6596 commented on src/Components/List/List.jsx
> +        </div>
готово

2020-09-10 10:49 UTC, Denchepornyuk approved these changes

2024-07-03 16:38 UTC, closed without merging